// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: protos/crawl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image       string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Price       string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Category    string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Dish) Reset() {
	*x = Dish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_crawl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_protos_crawl_proto_rawDescGZIP(), []int{0}
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dish) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Dish) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Dish) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CrawlDishesFromGoogleMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoogleMapUrl string `protobuf:"bytes,1,opt,name=googleMapUrl,proto3" json:"googleMapUrl,omitempty"`
}

func (x *CrawlDishesFromGoogleMapRequest) Reset() {
	*x = CrawlDishesFromGoogleMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_crawl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlDishesFromGoogleMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlDishesFromGoogleMapRequest) ProtoMessage() {}

func (x *CrawlDishesFromGoogleMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlDishesFromGoogleMapRequest.ProtoReflect.Descriptor instead.
func (*CrawlDishesFromGoogleMapRequest) Descriptor() ([]byte, []int) {
	return file_protos_crawl_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlDishesFromGoogleMapRequest) GetGoogleMapUrl() string {
	if x != nil {
		return x.GoogleMapUrl
	}
	return ""
}

type CrawlDishesFromGoogleMapReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Dish    []*Dish `protobuf:"bytes,3,rep,name=dish,proto3" json:"dish,omitempty"`
}

func (x *CrawlDishesFromGoogleMapReply) Reset() {
	*x = CrawlDishesFromGoogleMapReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_crawl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlDishesFromGoogleMapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlDishesFromGoogleMapReply) ProtoMessage() {}

func (x *CrawlDishesFromGoogleMapReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlDishesFromGoogleMapReply.ProtoReflect.Descriptor instead.
func (*CrawlDishesFromGoogleMapReply) Descriptor() ([]byte, []int) {
	return file_protos_crawl_proto_rawDescGZIP(), []int{2}
}

func (x *CrawlDishesFromGoogleMapReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrawlDishesFromGoogleMapReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CrawlDishesFromGoogleMapReply) GetDish() []*Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

var File_protos_crawl_proto protoreflect.FileDescriptor

var file_protos_crawl_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x22, 0x84, 0x01, 0x0a, 0x04,
	0x44, 0x69, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x22, 0x45, 0x0a, 0x1f, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4d,
	0x61, 0x70, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x55, 0x72, 0x6c, 0x22, 0x74, 0x0a, 0x1d, 0x43, 0x72, 0x61,
	0x77, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f,
	0x0a, 0x04, 0x64, 0x69, 0x73, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63,
	0x72, 0x61, 0x77, 0x6c, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x52, 0x04, 0x64, 0x69, 0x73, 0x68, 0x32,
	0x74, 0x0a, 0x06, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x12, 0x6a, 0x0a, 0x18, 0x43, 0x72, 0x61,
	0x77, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x26, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x2e, 0x43, 0x72,
	0x61, 0x77, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x63, 0x72, 0x61, 0x77, 0x6c, 0x2e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_crawl_proto_rawDescOnce sync.Once
	file_protos_crawl_proto_rawDescData = file_protos_crawl_proto_rawDesc
)

func file_protos_crawl_proto_rawDescGZIP() []byte {
	file_protos_crawl_proto_rawDescOnce.Do(func() {
		file_protos_crawl_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_crawl_proto_rawDescData)
	})
	return file_protos_crawl_proto_rawDescData
}

var file_protos_crawl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_crawl_proto_goTypes = []interface{}{
	(*Dish)(nil),                            // 0: crawl.Dish
	(*CrawlDishesFromGoogleMapRequest)(nil), // 1: crawl.CrawlDishesFromGoogleMapRequest
	(*CrawlDishesFromGoogleMapReply)(nil),   // 2: crawl.CrawlDishesFromGoogleMapReply
}
var file_protos_crawl_proto_depIdxs = []int32{
	0, // 0: crawl.CrawlDishesFromGoogleMapReply.dish:type_name -> crawl.Dish
	1, // 1: crawl.Spider.CrawlDishesFromGoogleMap:input_type -> crawl.CrawlDishesFromGoogleMapRequest
	2, // 2: crawl.Spider.CrawlDishesFromGoogleMap:output_type -> crawl.CrawlDishesFromGoogleMapReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_crawl_proto_init() }
func file_protos_crawl_proto_init() {
	if File_protos_crawl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_crawl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_crawl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlDishesFromGoogleMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_crawl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlDishesFromGoogleMapReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_crawl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_crawl_proto_goTypes,
		DependencyIndexes: file_protos_crawl_proto_depIdxs,
		MessageInfos:      file_protos_crawl_proto_msgTypes,
	}.Build()
	File_protos_crawl_proto = out.File
	file_protos_crawl_proto_rawDesc = nil
	file_protos_crawl_proto_goTypes = nil
	file_protos_crawl_proto_depIdxs = nil
}
