# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63rawl.proto\x12\x05\x63rawl\"Y\n\x04\x44ish\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\"7\n\x1f\x43rawlDishesFromGoogleMapRequest\x12\x14\n\x0cgoogleMapUrl\x18\x01 \x01(\t\"\\\n\x1d\x43rawlDishesFromGoogleMapReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x04\x64ish\x18\x03 \x03(\x0b\x32\x0b.crawl.Dish2t\n\x06Spider\x12j\n\x18\x43rawlDishesFromGoogleMap\x12&.crawl.CrawlDishesFromGoogleMapRequest\x1a$.crawl.CrawlDishesFromGoogleMapReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISH._serialized_start=22
  _DISH._serialized_end=111
  _CRAWLDISHESFROMGOOGLEMAPREQUEST._serialized_start=113
  _CRAWLDISHESFROMGOOGLEMAPREQUEST._serialized_end=168
  _CRAWLDISHESFROMGOOGLEMAPREPLY._serialized_start=170
  _CRAWLDISHESFROMGOOGLEMAPREPLY._serialized_end=262
  _SPIDER._serialized_start=264
  _SPIDER._serialized_end=380
# @@protoc_insertion_point(module_scope)
